eureka:
   client:
     register-with-eureka:true
     fetch-register:true
     service-url:
        defaultZone:http://localhost:8761/eureka/
   instance:
      hostname: loccalhost
      
 microservice:
    payment-service:
        endpoints:
          endpoint:
          url:http://PAYMENT-SERVICE/payment/doPayment
    order-service:
      endpoints:
          endpoint:
          url:http://ORDER-SERVICE/ORDER/bookOrder
                 
    
      
